{...}: {
  imports = [
    ./alpha.nix
    ./comment.nix
    ./conform.nix
    ./dap.nix
    ./dressing.nix
    ./flash.nix
    ./gitsigns.nix
    ./harpoon.nix
    ./indent-blankline.nix
    ./lazy-git.nix
    ./lint.nix
    ./lsp.nix
    ./lualine.nix
    ./neo-tree.nix
    ./neotest
    ./notebook.nix
    ./obsidian.nix
    ./oil.nix
    ./overseer
    ./persistence.nix
    ./rustaceanvim.nix
    ./snacks.nix
    ./surround.nix
    ./telescope.nix
    ./tmux-navigator.nix
    ./todo.nix
    ./treesitter.nix
    ./trouble.nix
    ./twilight.nix
    ./typst.nix
    ./ufo.nix
    ./undotree.nix
    ./vimtex.nix
    ./which-key.nix
    ./wrapping.nix
    ./zellij.nix
    ./zen_mode.nix
  ];
}
